[package]
name = "mem"
version = "0.1.0"
edition = "2021"
authors = ["Adrien Wald <hello@mrlowlevel.com>"]

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
